services:
  # API Gateway
  - name: api-gateway
    type: web
    env: node
    rootDir: api-gateway
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # User Service
  - name: user-service
    type: web
    env: node
    rootDir: services/user-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  # Product Service
  - name: product-service
    type: web
    env: node
    rootDir: services/product-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false

  # Cart Service
  - name: cart-service
    type: web
    env: node
    rootDir: services/cart-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false

  # Order Service
  - name: order-service
    type: web
    env: node
    rootDir: services/order-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false

  # Payment Service
  - name: payment-service
    type: web
    env: node
    rootDir: services/payment-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false

  # Notification Service
  - name: notification-service
    type: web
    env: node
    rootDir: services/notification-service
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false 